/**
 * Class Definitions — maps each class ID to its sprite, animations, and Q attack config.
 *
 * spriteKey    – texture key loaded in Preloader
 * isAtlas      – true if loaded via this.load.atlas (JSON), false if spritesheet
 * frameSize    – native frame pixel width (for display scaling)
 * frameHeight  – (optional) native frame pixel height if non-square; defaults to frameSize
 * displaySize  – (optional) override display size in pixels; default = max(48, frameSize*0.75)
 * feetRatio    – (optional) 0-1 ratio of where the character's feet sit in the frame (0=top, 1=bottom)
 * idleAnim     – animation key for idle
 * moveAnim     – animation key for movement
 * attackAnim   – animation key for the Q special attack (null = no class attack)
 * attackName   – display name for HUD
 * attackCooldown – ms cooldown
 * attackType   – dispatcher key used in Level1._handleClassAttack()
 * ... extra params per attack type
 */

export const CLASS_DEFS = Object.freeze({
    barbarian: {
        id: 'barbarian',
        className: 'Barbarian',
        color: 0xFF4444,
        description: 'Kill-chaining, melee, self-sustain',
        spriteKey: 'barbarian',
        isAtlas: true,
        frameSize: 96,
        displaySize: 88,
        feetRatio: 0.58,
        idleAnim: 'barbarian_idle',
        moveAnim: 'barbarian_move',
        attackAnim: 'barbarian_spin',
        attackName: 'Berserker Charge',
        attackDesc: 'Charge forward; banish all enemies in path (+8 Flame/kill)',
        attackCooldown: 8000,
        attackType: 'berserker_charge',
        chargeDistance: 210,
        chargeFlamePerKill: 8,
        sAbility: { type: 'war_cry', stunDuration: 2000, drainMult: 0.6, drainDuration: 3000, cooldown: 10000, desc: 'Stun all on-screen enemies; reduce flame drain for 3s' },
        eAbility: { type: 'war_howl', stunRadius: 200, stunDuration: 1500, cooldown: 6000, desc: 'Reset Q cooldown; stun enemies in 200px for 1.5s' },
        passive: { id: 'kill_fuel', flamePerKill: 6, description: '+6 Flame per kill' },
    },

    wizard: {
        id: 'wizard',
        className: 'Wizard',
        color: 0x4488FF,
        description: 'AoE damage, cooldowns, elemental',
        spriteKey: 'elite_mage',
        isAtlas: true,
        frameSize: 64,
        frameHeight: 32,
        displaySize: 80,
        feetRatio: 0.90,
        idleAnim: 'elite_mage_idle',
        moveAnim: 'elite_mage_move',
        attackAnim: 'elite_mage_attack3',
        attackName: 'Arcane Blast',
        attackDesc: 'AoE banish all enemies within 240px',
        attackCooldown: 7500,
        attackType: 'aoe_banish',
        attackRadius: 240,
        stunRadius: 0,
        stunDuration: 0,
        sAbility: { type: 'arcane_mine', radius: 120, detonateDelay: 1000, cooldown: 9000, desc: 'Drop mine; detonates after 1s with 120px AoE banish' },
        eAbility: { type: 'mana_shield', invincDuration: 3000, banishRadius: 180, cooldown: 7000, desc: '3s invincibility; on expiry burst-banish within 180px' },
        passive: { id: 'mana_surge', description: 'Q cooldown 25% shorter; blast radius +40px' },
    },

    ranger: {
        id: 'ranger',
        className: 'Ranger',
        color: 0x44DD66,
        description: 'Mobility, ranged, evasion',
        spriteKey: 'elven_archeress',
        isAtlas: true,
        frameSize: 64,
        frameHeight: 32,
        displaySize: 80,
        feetRatio: 0.90,
        idleAnim: 'elven_archeress_idle',
        moveAnim: 'elven_archeress_move',
        attackAnim: 'elven_archeress_take_aim',
        attackName: 'Rapid Shot',
        attackDesc: 'Fire 3 rapid arrows; each banishes the first enemy hit',
        attackCooldown: 4500,
        attackType: 'arrow_shot',
        arrowSpeed: 620,
        arrowCount: 3,
        sAbility: { type: 'volley', arrowCount: 5, arrowSpeed: 620, spreadDeg: 20, cooldown: 7000, desc: '5-arrow fan volley; each arrow banishes on contact' },
        eAbility: { type: 'eagle_eye', slowScale: 0.3, duration: 2000, cooldown: 6000, desc: 'Slow world to 30% speed for 2s (real time)' },
        passive: { id: 'fleet_footed', flamePerDash: 4, invincDuration: 800, description: '+4 Flame & brief invincibility on dash' },
    },

    tank: {
        id: 'tank',
        className: 'Tank',
        color: 0xCCCCCC,
        description: 'Defense, damage reduction, parry',
        spriteKey: 'elite_knight',
        isAtlas: true,
        frameSize: 96,
        displaySize: 84,
        feetRatio: 0.60,
        idleAnim: 'elite_knight_idle',
        moveAnim: 'elite_knight_move',
        attackAnim: 'elite_knight_block',
        attackName: 'Shield Block',
        attackDesc: '3s invincibility; touching enemies during shield banishes them',
        attackCooldown: 12000,
        attackType: 'shield',
        shieldDuration: 3000,
        sAbility: { type: 'iron_stance', invincDuration: 3000, cooldown: 12000, desc: '3s invincibility; contact-banish any enemy during stance' },
        eAbility: { type: 'fortify', healAmount: 40, cooldown: 8000, desc: 'Instantly restore 40 Flame' },
        passive: { id: 'iron_will', flameThreshold: 30, drainReduction: 0.40, description: 'Drain -40% when Flame \u2264 30' },
    },

    healer: {
        id: 'healer',
        className: 'Healer',
        color: 0x88DDFF,
        description: 'Flame sustain, wisps, auras',
        spriteKey: 'royal_mage',
        isAtlas: true,
        frameSize: 32,
        displaySize: 56,
        idleAnim: 'royal_mage_idle',
        moveAnim: 'royal_mage_move',
        attackAnim: 'royal_mage_attack',
        attackName: 'Heal Pulse',
        attackDesc: 'Restore 35 Flame; halve flame drain for 5s',
        attackCooldown: 12000,
        attackType: 'heal',
        healAmount: 35,
        drainReduction: 0.5,
        drainReductionDuration: 5000,
        sAbility: { type: 'mend', healAmount: 30, drainMult: 0.5, drainDuration: 4000, cooldown: 10000, desc: 'Restore 30 Flame; halve flame drain for 4s' },
        eAbility: { type: 'regen_pulse', rate: 8, duration: 4000, cooldown: 7000, desc: 'Regenerate 8 Flame/s for 4s' },
        passive: { id: 'warding_light', wispMagnetMult: 2.0, wispRestoreMult: 1.5, description: 'Wisp magnet range \xd72 & restore \xd71.5' },
    },

    assassin: {
        id: 'assassin',
        className: 'Assassin',
        color: 0xAA44FF,
        description: 'Speed, positioning, burst',
        spriteKey: 'elven_assassin',
        isAtlas: true,
        frameSize: 64,
        frameHeight: 32,
        displaySize: 80,
        feetRatio: 0.90,
        idleAnim: 'elven_assassin_idle',
        moveAnim: 'elven_assassin_move',
        attackAnim: 'elven_assassin_disappear',
        attackName: 'Shadow Blink',
        attackDesc: 'Blink forward 130px; banish all enemies in path',
        attackCooldown: 7000,
        attackType: 'blink',
        blinkDistance: 130,
        sAbility: { type: 'vanish', invisDuration: 2500, cooldown: 9000, desc: '2.5s invisibility + invincibility; burst VFX on emerge' },
        eAbility: { type: 'lethal_mark', flameReward: 30, markDuration: 3000, cooldown: 5000, desc: 'Next banish within 3s restores +30 Flame' },
        passive: { id: 'shadow_strike', dashKillFlame: 18, normalKillFlame: 3, description: '+18 Flame on dash-kill, +3 on normal kill' },
    },

    adventurer: {
        id: 'adventurer',
        className: 'Adventurer',
        color: 0xFFCC00,
        description: 'Jack of all trades — generic survival',
        spriteKey: 'adventurer',
        isAtlas: false,
        frameSize: 32,
        displaySize: 56,
        idleAnim: 'adventurer_idle',
        moveAnim: 'adventurer_move',
        attackAnim: 'adventurer_attack',
        attackName: 'Flame Strike',
        attackDesc: 'Banish closest enemy within 70px; reset dash cooldown',
        attackCooldown: 8000,
        attackType: 'melee_banish',
        attackRadius: 70,
        sAbility: { type: 'smoke_bomb', radius: 200, stunDuration: 2500, flameRestore: 8, cooldown: 8000, desc: 'Stun enemies in 200px ahead; restore 8 Flame' },
        eAbility: { type: 'flame_burst', radius: 130, cooldown: 8000, desc: 'AoE push & banish all enemies within 130px' },
        passive: { id: 'adaptable', drainReductionPerRelic: 0.05, maxRelics: 3, description: '+5% drain reduction per active relic (max 3)' },
    },

    monk: {
        id: 'monk',
        className: 'Monk',
        color: 0x44DD66,
        description: 'Defensive/offensive hybrid, knockback specialist',
        spriteKey: 'monk',
        isAtlas: true,
        frameSize: 96,
        displaySize: 88,
        feetRatio: 0.58,
        idleAnim: 'monk_idle',
        moveAnim: 'monk_move',
        attackAnim: 'monk_spin',
        attackName: 'Staff Spin',
        attackDesc: 'Knockback all enemies in 130px; stun for 1.5s',
        attackCooldown: 6000,
        attackType: 'knockback',
        attackRadius: 130,
        pushDistance: 300,
        stunDuration: 1500,
        sAbility: { type: 'chi_wave', speed: 300, stunDuration: 1800, radius: 30, cooldown: 7000, desc: 'Launch slow chi orb; stuns all enemies it passes through' },
        eAbility: { type: 'chi_strike', pushRadius: 200, pushDistance: 150, cooldown: 5000, desc: 'Banish closest enemy; push all others in 200px' },
        passive: { id: 'iron_palm', radius: 120, pushSpeed: 200, description: 'Each kill knocks back nearby enemies (120px, speed 200)' },
    },

    duelist: {
        id: 'duelist',
        className: 'Duelist',
        color: 0xFFCC00,
        description: 'Melee burst, precision strikes',
        spriteKey: 'elite_swordsman',
        isAtlas: true,
        frameSize: 96,
        displaySize: 88,
        feetRatio: 0.58,
        idleAnim: 'elite_swordsman_idle',
        moveAnim: 'elite_swordsman_move',
        attackAnim: 'elite_swordsman_attack1',
        attackName: 'Dual Strike',
        attackDesc: 'Two-hit frontal attack — stun then banish within 80px',
        attackCooldown: 6000,
        attackType: 'dual_strike',
        attackRadius: 80,
        sAbility: { type: 'blade_storm', radius: 120, cooldown: 9000, desc: 'AoE banish in 120px radius; reset Q cooldown' },
        eAbility: { type: 'parry_stance', parryDuration: 1500, parryFlame: 8, cooldown: 5000, desc: '1.5s parry; banishing during parry restores +8 Flame' },
        passive: { id: 'duelist_rhythm', killInterval: 3, bonusElixir: 10, description: 'Every 3rd kill grants +10 Elixir' },
    },

    pyromancer: {
        id: 'pyromancer',
        className: 'Pyromancer',
        color: 0xFF6600,
        description: 'Fire DoT, area denial',
        spriteKey: 'pyromancer',
        isAtlas: false,
        frameSize: 32,
        displaySize: 56,
        idleAnim: 'pyromancer_idle',
        moveAnim: 'pyromancer_move',
        attackAnim: 'pyromancer_attack',
        attackName: 'Fireball',
        attackDesc: 'Launch fireball; banishes first enemy hit (60px splash)',
        attackCooldown: 7000,
        attackType: 'flame_projectile',
        projectileSpeed: 350,
        projectileRadius: 60,
        sAbility: { type: 'inferno', radius: 120, duration: 3000, tickDamage: 10, tickInterval: 500, cooldown: 8000, desc: 'Create fire zone at feet for 3s; damages all enemies inside' },
        eAbility: { type: 'combustion_burst', damage: 40, cooldown: 8000, desc: 'Instantly damage all active enemies; banish those at 1 HP' },
        passive: { id: 'combustion', radius: 70, duration: 1500, description: 'Each kill leaves a 1.5s fire zone (70px radius)' },
    },
});

/** Default class before any class is selected — uses the adventurer sprite */
export const DEFAULT_CLASS = CLASS_DEFS.adventurer;
