/**
 * Class Definitions — maps each skill ID to its class sprite, animations, and attack config.
 *
 * spriteKey    – texture key loaded in Preloader
 * isAtlas      – true if loaded via this.load.atlas (JSON), false if spritesheet
 * frameSize    – native frame pixel width (for display scaling)
 * frameHeight  – (optional) native frame pixel height if non-square; defaults to frameSize
 * displaySize  – (optional) override display size in pixels; default = max(48, frameSize*0.75)
 * feetRatio    – (optional) 0-1 ratio of where the character's feet sit in the frame (0=top, 1=bottom)
 * idleAnim     – animation key for idle
 * moveAnim     – animation key for movement
 * attackAnim   – animation key for the Q special attack (null = no class attack)
 * attackName   – display name for HUD
 * attackCooldown – ms cooldown
 * attackType   – dispatcher key used in Level1._handleClassAttack()
 * ... extra params per attack type
 */

export const CLASS_DEFS = Object.freeze({
    // ── Red (Combat) ──
    earthshatter: {
        className: 'Barbarian',
        spriteKey: 'barbarian',
        isAtlas: true,
        frameSize: 96,
        displaySize: 112,
        feetRatio: 0.58,
        idleAnim: 'barbarian_idle',
        moveAnim: 'barbarian_move',
        attackAnim: 'barbarian_spin',
        attackName: 'Spin Attack',
        attackCooldown: 8000,
        attackType: 'aoe_banish',
        attackRadius: 120,
        stunRadius: 180,
        stunDuration: 2000,
    },
    flameCleave: {
        className: 'Warrior',
        spriteKey: 'elite_swordsman',
        isAtlas: true,
        frameSize: 96,
        displaySize: 104,
        feetRatio: 0.65,
        idleAnim: 'elite_swordsman_idle',
        moveAnim: 'elite_swordsman_move',
        attackAnim: 'elite_swordsman_attack2',
        attackName: 'Cleave',
        attackCooldown: 6000,
        attackType: 'frontal_banish',
        attackRadius: 80,
    },
    aerialFury: {
        className: 'Athlete',
        spriteKey: 'monk',
        isAtlas: true,
        frameSize: 96,
        displaySize: 108,
        feetRatio: 0.67,
        idleAnim: 'monk_idle',
        moveAnim: 'monk_move',
        attackAnim: 'monk_spin',
        attackName: 'Staff Spin',
        attackCooldown: 7000,
        attackType: 'knockback',
        pushDistance: 200,
        stunDuration: 2000,
        attackRadius: 120,
    },
    emberWard: {
        className: 'Tank',
        spriteKey: 'elite_knight',
        isAtlas: true,
        frameSize: 96,
        displaySize: 108,
        feetRatio: 0.60,
        idleAnim: 'elite_knight_idle',
        moveAnim: 'elite_knight_move',
        attackAnim: 'elite_knight_block',
        attackName: 'Shield Block',
        attackCooldown: 12000,
        attackType: 'shield',
        shieldDuration: 4000,
    },

    // ── Blue (Flame/Magic) ──
    infernoNova: {
        className: 'Wizard',
        spriteKey: 'elite_mage',
        isAtlas: true,
        frameSize: 64,
        frameHeight: 32,
        displaySize: 104,
        feetRatio: 0.90,
        idleAnim: 'elite_mage_idle',
        moveAnim: 'elite_mage_move',
        attackAnim: 'elite_mage_attack3',
        attackName: 'Arcane Blast',
        attackCooldown: 10000,
        attackType: 'aoe_banish',
        attackRadius: 200,
        stunRadius: 0,
        stunDuration: 0,
        useBlastVFX: true,
    },
    wardingFlame: {
        className: 'Battlemage',
        spriteKey: 'pyromancer',
        isAtlas: false,
        frameSize: 32,
        idleAnim: 'pyromancer_idle',
        moveAnim: 'pyromancer_move',
        attackAnim: 'pyromancer_attack',
        attackName: 'Fire Nova',
        attackCooldown: 8000,
        attackType: 'aoe_banish',
        attackRadius: 100,
        stunRadius: 160,
        stunDuration: 3000,
    },
    kindlingSpirit: {
        className: 'Healer',
        spriteKey: 'royal_mage',
        isAtlas: true,
        frameSize: 32,
        idleAnim: 'royal_mage_idle',
        moveAnim: 'royal_mage_move',
        attackAnim: 'royal_mage_attack',
        attackName: 'Heal Pulse',
        attackCooldown: 15000,
        attackType: 'heal',
        healAmount: 30,
        drainReduction: 0.5,
        drainReductionDuration: 5000,
    },
    riposteDash: {
        className: 'Trickster',
        spriteKey: 'adventurer',
        isAtlas: false,
        frameSize: 32,
        idleAnim: 'adventurer_idle',
        moveAnim: 'adventurer_move',
        attackAnim: 'adventurer_attack',
        attackName: 'Quick Strike',
        attackCooldown: 5000,
        attackType: 'melee_banish',
    },
    elixirBolt: {
        className: 'Arcane Archer',
        spriteKey: 'elven_archeress',
        isAtlas: true,
        frameSize: 64,
        frameHeight: 32,
        displaySize: 104,
        feetRatio: 0.90,
        idleAnim: 'elven_archeress_idle',
        moveAnim: 'elven_archeress_move',
        attackAnim: 'elven_archeress_release',
        attackName: 'Power Shot',
        attackCooldown: 6000,
        attackType: 'projectile',
        projectileRange: 400,
        projectileSpeed: 500,
        grantsElixir: true,
    },

    // ── Green (Mobility/Survival) ──
    windRunner: {
        className: 'Ranger',
        spriteKey: 'elven_archeress',
        isAtlas: true,
        frameSize: 64,
        frameHeight: 32,
        displaySize: 104,
        feetRatio: 0.90,
        idleAnim: 'elven_archeress_idle',
        moveAnim: 'elven_archeress_move',
        attackAnim: 'elven_archeress_take_aim',
        attackName: 'Arrow Rain',
        attackCooldown: 8000,
        attackType: 'screen_stun',
        stunDuration: 3000,
    },
    shadowStep: {
        className: 'Assassin',
        spriteKey: 'elven_assassin',
        isAtlas: true,
        frameSize: 64,
        frameHeight: 32,
        displaySize: 104,
        feetRatio: 0.90,
        idleAnim: 'elven_assassin_idle',
        moveAnim: 'elven_assassin_move',
        attackAnim: 'elven_assassin_disappear',
        attackName: 'Shadow Blink',
        attackCooldown: 7000,
        attackType: 'blink',
        blinkDistance: 150,
    },
    spiritCompanion: {
        className: 'Beast Master',
        spriteKey: 'rogue',
        isAtlas: false,
        frameSize: 32,
        idleAnim: 'rogue_idle',
        moveAnim: 'rogue_move',
        attackAnim: 'rogue_attack',
        attackName: 'Throw Knife',
        attackCooldown: 5000,
        attackType: 'projectile',
        projectileRange: 200,
        projectileSpeed: 400,
        grantsElixir: false,
        flameRestore: 5,
    },

    // ── Passive classes (no class attack) ──
    emberveil: {
        className: 'Survivor',
        spriteKey: 'adventurer',
        isAtlas: false,
        frameSize: 32,
        idleAnim: 'adventurer_idle',
        moveAnim: 'adventurer_move',
        attackAnim: null,
        attackName: null,
        attackCooldown: 0,
        attackType: null,
    },
    elixirSiphon: {
        className: 'Core',
        spriteKey: 'adventurer',
        isAtlas: false,
        frameSize: 32,
        idleAnim: 'adventurer_idle',
        moveAnim: 'adventurer_move',
        attackAnim: null,
        attackName: null,
        attackCooldown: 0,
        attackType: null,
    },
});

/** Default class before any skill is chosen — uses the adventurer sprite */
export const DEFAULT_CLASS = Object.freeze({
    className: null,
    spriteKey: 'adventurer',
    isAtlas: false,
    frameSize: 32,
    idleAnim: 'adventurer_idle',
    moveAnim: 'adventurer_move',
    attackAnim: null,
    attackName: null,
    attackCooldown: 0,
    attackType: null,
});
