/**
 * Class Definitions — maps each class ID to its sprite, animations, and Q attack config.
 *
 * spriteKey    – texture key loaded in Preloader
 * isAtlas      – true if loaded via this.load.atlas (JSON), false if spritesheet
 * frameSize    – native frame pixel width (for display scaling)
 * frameHeight  – (optional) native frame pixel height if non-square; defaults to frameSize
 * displaySize  – (optional) override display size in pixels; default = max(48, frameSize*0.75)
 * feetRatio    – (optional) 0-1 ratio of where the character's feet sit in the frame (0=top, 1=bottom)
 * idleAnim     – animation key for idle
 * moveAnim     – animation key for movement
 * attackAnim   – animation key for the Q special attack (null = no class attack)
 * attackName   – display name for HUD
 * attackCooldown – ms cooldown
 * attackType   – dispatcher key used in Level1._handleClassAttack()
 * ... extra params per attack type
 */

export const CLASS_DEFS = Object.freeze({
    barbarian: {
        id: 'barbarian',
        className: 'Barbarian',
        color: 0xFF4444,
        description: 'Kill-chaining, melee, self-sustain',
        spriteKey: 'barbarian',
        isAtlas: true,
        frameSize: 96,
        displaySize: 112,
        feetRatio: 0.58,
        idleAnim: 'barbarian_idle',
        moveAnim: 'barbarian_move',
        attackAnim: 'barbarian_spin',
        attackName: 'Spin Attack',
        attackCooldown: 8000,
        attackType: 'aoe_banish',
        attackRadius: 120,
        stunRadius: 180,
        stunDuration: 2000,
        sAbility: { type: 'earthshatter', radius: 200, knockback: 400, stunDuration: 2500 },
    },

    wizard: {
        id: 'wizard',
        className: 'Wizard',
        color: 0x4488FF,
        description: 'AoE damage, cooldowns, elemental',
        spriteKey: 'elite_mage',
        isAtlas: true,
        frameSize: 64,
        frameHeight: 32,
        displaySize: 104,
        feetRatio: 0.90,
        idleAnim: 'elite_mage_idle',
        moveAnim: 'elite_mage_move',
        attackAnim: 'elite_mage_attack3',
        attackName: 'Arcane Blast',
        attackCooldown: 10000,
        attackType: 'aoe_banish',
        attackRadius: 200,
        stunRadius: 0,
        stunDuration: 0,
        useBlastVFX: true,
        sAbility: { type: 'arcane_mine', radius: 120, detonateDelay: 1000 },
    },

    ranger: {
        id: 'ranger',
        className: 'Ranger',
        color: 0x44DD66,
        description: 'Mobility, ranged, evasion',
        spriteKey: 'elven_archeress',
        isAtlas: true,
        frameSize: 64,
        frameHeight: 32,
        displaySize: 104,
        feetRatio: 0.90,
        idleAnim: 'elven_archeress_idle',
        moveAnim: 'elven_archeress_move',
        attackAnim: 'elven_archeress_take_aim',
        attackName: 'Arrow Rain',
        attackCooldown: 7000,
        attackType: 'screen_stun',
        stunDuration: 3000,
        maxBanish: 2,
        sAbility: { type: 'arrow_rain', width: 300, stunDuration: 1500 },
    },

    tank: {
        id: 'tank',
        className: 'Tank',
        color: 0xCCCCCC,
        description: 'Defense, damage reduction, parry',
        spriteKey: 'elite_knight',
        isAtlas: true,
        frameSize: 96,
        displaySize: 108,
        feetRatio: 0.60,
        idleAnim: 'elite_knight_idle',
        moveAnim: 'elite_knight_move',
        attackAnim: 'elite_knight_block',
        attackName: 'Shield Block',
        attackCooldown: 12000,
        attackType: 'shield',
        shieldDuration: 3000,
        sAbility: { type: 'fortress_drop', barrierDuration: 3000, radius: 150, stunDuration: 2000 },
    },

    healer: {
        id: 'healer',
        className: 'Healer',
        color: 0x88DDFF,
        description: 'Flame sustain, wisps, auras',
        spriteKey: 'royal_mage',
        isAtlas: true,
        frameSize: 32,
        idleAnim: 'royal_mage_idle',
        moveAnim: 'royal_mage_move',
        attackAnim: 'royal_mage_attack',
        attackName: 'Heal Pulse',
        attackCooldown: 12000,
        attackType: 'heal',
        healAmount: 35,
        drainReduction: 0.5,
        drainReductionDuration: 5000,
        sAbility: { type: 'purifying_landing', healPerSec: 12, duration: 4000, radius: 150 },
    },

    assassin: {
        id: 'assassin',
        className: 'Assassin',
        color: 0xAA44FF,
        description: 'Speed, positioning, burst',
        spriteKey: 'elven_assassin',
        isAtlas: true,
        frameSize: 64,
        frameHeight: 32,
        displaySize: 104,
        feetRatio: 0.90,
        idleAnim: 'elven_assassin_idle',
        moveAnim: 'elven_assassin_move',
        attackAnim: 'elven_assassin_disappear',
        attackName: 'Shadow Blink',
        attackCooldown: 7000,
        attackType: 'blink',
        blinkDistance: 130,
        sAbility: { type: 'shadow_dive', invisDuration: 1500 },
    },

    adventurer: {
        id: 'adventurer',
        className: 'Adventurer',
        color: 0xFFCC00,
        description: 'Jack of all trades — generic survival',
        spriteKey: 'adventurer',
        isAtlas: false,
        frameSize: 32,
        idleAnim: 'adventurer_idle',
        moveAnim: 'adventurer_move',
        attackAnim: 'adventurer_attack',
        attackName: 'Flame Strike',
        attackCooldown: 8000,
        attackType: 'melee_banish',
        attackRadius: 70,
        sAbility: { type: 'ground_slam' },
    },

    monk: {
        id: 'monk',
        className: 'Monk',
        color: 0x44DD66,
        description: 'Defensive/offensive hybrid, knockback specialist',
        spriteKey: 'monk',
        isAtlas: true,
        frameSize: 96,
        displaySize: 112,
        feetRatio: 0.58,
        idleAnim: 'monk_idle',
        moveAnim: 'monk_move',
        attackAnim: 'monk_spin',
        attackName: 'Staff Spin',
        attackCooldown: 6000,
        attackType: 'knockback',
        attackRadius: 130,
        pushDistance: 300,
        stunDuration: 1500,
        sAbility: { type: 'staff_pogo', radius: 100, stunDuration: 2000 },
    },

    duelist: {
        id: 'duelist',
        className: 'Duelist',
        color: 0xFFCC00,
        description: 'Melee burst, precision strikes',
        spriteKey: 'elite_swordsman',
        isAtlas: true,
        frameSize: 96,
        displaySize: 112,
        feetRatio: 0.58,
        idleAnim: 'elite_swordsman_idle',
        moveAnim: 'elite_swordsman_move',
        attackAnim: 'elite_swordsman_attack1',
        attackName: 'Dual Strike',
        attackCooldown: 6000,
        attackType: 'dual_strike',
        attackRadius: 80,
        sAbility: { type: 'piercing_thrust', radius: 80, stunDuration: 2500 },
    },

    pyromancer: {
        id: 'pyromancer',
        className: 'Pyromancer',
        color: 0xFF6600,
        description: 'Fire DoT, area denial',
        spriteKey: 'pyromancer',
        isAtlas: false,
        frameSize: 32,
        idleAnim: 'pyromancer_idle',
        moveAnim: 'pyromancer_move',
        attackAnim: 'pyromancer_attack',
        attackName: 'Fireball',
        attackCooldown: 7000,
        attackType: 'flame_projectile',
        projectileSpeed: 350,
        projectileRadius: 60,
        sAbility: { type: 'meteor_drop', width: 120, duration: 2500 },
    },
});

/** Default class before any class is selected — uses the adventurer sprite */
export const DEFAULT_CLASS = CLASS_DEFS.adventurer;
